version: '3.8'

services:
  # Minimal Qdrant setup
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/qdrant:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO

networks:
  default:
    name: qdrant-network